# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ Project:     OmniCores-Registers                                          ║
# ║ Author:      Louis Duret-Robert - louisduret@gmail.com                    ║
# ║ Website:     louis-dr.github.io                                           ║
# ║ License:     MIT License                                                  ║
# ╟───────────────────────────────────────────────────────────────────────────╢
# ║ Description: Generation method of the register bank. It configures the    ║
# ║              rendering engine, feeds it the data structure, and renders   ║
# ║              each template.                                               ║
# ╚═══════════════════════════════════════════════════════════════════════════╝



import j2gpp
import importlib
from pathlib import Path



def render_template(render_engine:j2gpp.J2GPP, template_path:str|Path, output_path:str|Path):
  """Render a template from the library package to a given path."""
  # Rendering with exception handling
  try:
    # Load template from package resources
    template_path_reference = importlib.resources.files('omnicores_register').joinpath(template_path)
    with importlib.resources.as_file(template_path_reference) as template_path_object:
      template_path_string = str(template_path_object)
      # Render the template file to the output path
      render_results = render_engine.render_file(template_path_string, output_path)
      # Check success
      if render_results.success:
        print(f"Successfully generated file '{output_path}'.")
      else:
        print(f"ERROR: Could not render the template '{template_path}': {render_results.error_message}")
        exit(1)
  # Exception handling
  except FileNotFoundError:
    print(f"ERROR: Template file '{template_path}' not found in package.")
    exit(1)
  except Exception as exception:
    print(f"ERROR: {exception}.")
    exit(1)



def generate(self):
  """Generate all files of the register bank after configuration and elaboration."""
  # J2GPP environment
  render_engine = j2gpp.J2GPP()
  render_engine.load_extensions()
  render_engine.set_option('trim_whitespace', True)

  # Header warning for generated files
  render_engine.define_variable('header_warning_generated_file', """
// ╟───────────────────────────────────────────────────────────────────────────╢
// ║ Generated:   This file has been generated by OmniCores-Registers. Please  ║
// ║              refer to the original configuration source script.           ║""")

  # Pass the data structure to the template engine for use in templates
  render_engine.define_variable('register_bank', self)

  # Path objects
  register_bank_name = f'{self.name}__register_bank'
  template_folder    = Path('templates')
  output_folder      = Path(register_bank_name)

  # Render each templates
  render_template(render_engine, template_folder / 'register_bank.sv.j2', output_folder/ f'{register_bank_name}.sv')
  render_template(render_engine, template_folder / 'package.sv.j2',       output_folder/ f'{register_bank_name}.package.sv')
  render_template(render_engine, template_folder / 'testbench.sv.j2',     output_folder/ f'{register_bank_name}.testbench.sv')
